
Main.class: Main.java AbstractBoard.java  BoardArray1D.java BoardArray2D.java 
	javac  Main.java AbstractBoard.java  BoardArray1D.java  BoardArray2D.java 

$(info To Run This Program Please Enter => java Main)
clean: 
	$(RM) *.class

