
Main.class: Main.java GTUContainer.java  GTUSet.java GTUVector.java 
	javac  Main.java GTUContainer.java  GTUSet.java  GTUVector.java 

$(info To Run This Program Please Enter => java Main)
clean: 
	$(RM) *.class

